---
kind: pipeline
type: docker
name: default

steps:
- name: restore-cache-with-filesystem
  image: meltwater/drone-cache
  pull: true
  settings:
    backend: "filesystem"
    restore: true
    cache_key: '{{ .Commit.Branch }}'
    archive_format: "gzip"
    filesystem_cache_root: "/var/lib/cache"
    mount:
      - "target"
      - "frontend/node_modules"
  volumes:
    - name: cache
      path: "/var/lib/cache"

- name: build-and-test-rust
  image: registry.husk.pro/just-rust-docker:1.56
  environment:
    HTB_TEAM_ID:
      from_secret: HTB_TEAM_ID
    HTB_EMAIL:
      from_secret: HTB_EMAIL
    HTB_PASSWORD:
      from_secret: HTB_PASSWORD
  commands:
  - just check
  - just test
  depends_on: [ clone, restore-cache-with-filesystem ] 

- name: build-frontend
  image: node:16
  commands:
  - cd frontend
  - npm install
  - npm run build
  depends_on: [ clone ]

- name: rebuild-cache-with-filesystem
  image: meltwater/drone-cache
  pull: true
  depends_on: [ clone, build-and-test-rust ]
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: '{{ .Commit.Branch }}'
    archive_format: "gzip"
    filesystem_cache_root: "/var/lib/cache"    
    mount:
      - "target"
      - "frontend/node_modules"
  volumes:
    - name: cache
      path: "/var/lib/cache"

volumes:
  - name: cache
    host:
      path: "/var/lib/cache"
---
kind: signature
hmac: cfc0afbc19064e06ee7ad5278c26474bbc912ff4c661227c45e3bbc3a0a83687

...
