kind: pipeline
type: docker
name: default

steps:
- name: build and test rust
  image: registry.husk.pro/just-rust-docker:1.56
  environment:
    HTB_TEAM_ID:
      from_secret: HTB_TEAM_ID
    HTB_EMAIL:
      from_secret: HTB_EMAIL
    HTB_PASSWORD:
      from_secret: HTB_PASSWORD
  commands:
  - just check
  - just test
  depends_on: [ clone ] 

- name: build-frontend
  image: node:16
  commands:
  - cd frontend
  - npm install
  - npm run build
  depends_on: [ clone ] 