name: Project CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: bot
      - name: Build bot
        run: cd bot && cargo build --verbose
      - name: Run tests for bot
        run: cd bot && cargo test --verbose

  db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ctfdb
      - name: Build ctfdb
        run: cd ctfdb && cargo build --verbose
      - name: Run tests for ctfdb
        run: cd ctfdb && cargo test --verbose

  rest-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: rest-api
      - name: Build rest-api
        run: cd rest-api && cargo build --verbose
      - name: Run tests for rest-api
        run: cd rest-api && cargo test --verbose

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd frontend && npm install
      - run: cd frontend && npm run build --if-present
