name: Project CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: .
      - name: Build rust projects 
        run: cargo build --verbose
      - name: Run tests for all rust projects
        env:
          HTB_EMAIL: ${{ secrets.HTB_EMAIL }}
          HTB_PASSWORD: ${{ secrets.HTB_PASSWORD }}
          HTB_TEAM_ID: ${{ secrets.HTB_TEAM_ID }}
        run: cargo test --verbose

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd frontend && npm install
      - run: cd frontend && npm run build --if-present
