name: Release

on:
  push:
    branches:
      - main

jobs:
  docker-release-bot:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
        with:
          file: bot.Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/huskehhh/ctfd_rs_bot:latest
            ghcr.io/huskehhh/ctfd_rs_bot:$PROJECT_VERSION

  docker-release-api:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
        with:
          file: rest-api.Dockerfile
          context: .
          push: true
          tags: | 
            ghcr.io/huskehhh/ctfd_rs_api:latest
            ghcr.io/huskehhh/ctfd_rs_api:$PROJECT_VERSION

  docker-release-ui:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        with:
          file: frontend/frontend.Dockerfile
          context: frontend/
          push: true
          tags: | 
            ghcr.io/huskehhh/ctfd_rs_ui:latest
            ghcr.io/huskehhh/ctfd_rs_ui:$PROJECT_VERSION
