name: Release

on:
  push:
    branches:
      - main

jobs:
  docker-release-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: bot.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            Huskehhh/ctfd_rs_bot:latest
            ghcr.io/Huskehhh/ctfd_rs_bot:latest

  docker-release-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: rest-api.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: | 
            Huskehhh/ctfd_rs_api:latest
            ghcr.io/Huskehhh/ctfd_rs_api:latest

  docker-release-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: frontend/frontend.Dockerfile
          context: frontend/
          platforms: linux/arm64
          push: true
          tags: | 
            Huskehhh/ctfd_rs_ui:latest
            ghcr.io/Huskehhh/ctfd_rs_ui:latest
